" Name:         Handarbeit
" Description:  Colorscheme based on the Cherry G81-3000HBD keyboard
" Author:       Christopher Milan <chrismilan@ucla.edu>
" Maintainer:   Christopher Milan <chrismilan@ucla.edu>
" License:      Public domain
" Last Updated: Sun Sep  7 10:06:58 2025

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'handarbeit'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#3a3a3a', '#c9503f', '#007730', '#e5a100', '#2f77a5', '#6d557e', '#19717e', '#d0d0d0', '#6c6c6c', '#c87e74', '#689b30', '#f2d07f', '#7fabc7', '#aea1b7', '#7fa580', '#eeeeee']
endif
hi Normal guifg=#eeeeee guibg=#000000 gui=NONE cterm=NONE
hi Cursor guifg=#262626 guibg=#eeeeee gui=NONE cterm=NONE
hi None guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi CursorLineNr guifg=#d0d0d0 guibg=#3a3a3a gui=NONE cterm=NONE
hi FoldColumn guifg=#6c6c6c guibg=#000000 gui=NONE cterm=NONE
hi Folded guifg=#6c6c6c guibg=#000000 gui=NONE cterm=NONE
hi LineNr guifg=#6c6c6c guibg=#000000 gui=NONE cterm=NONE
hi MatchParen guifg=#eeeeee guibg=#000000 gui=bold cterm=bold
hi SignColumn guifg=#6c6c6c guibg=#000000 gui=NONE cterm=NONE
hi Ignore guifg=#585858 guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#949494 guibg=#3a3a3a gui=NONE cterm=NONE
hi PmenuSbar guifg=#000000 guibg=#000000 gui=NONE cterm=NONE
hi PmenuSel guifg=#eeeeee guibg=#444444 gui=NONE cterm=NONE
hi PmenuThumb guifg=#585858 guibg=#585858 gui=NONE cterm=NONE
hi ErrorMsg guifg=#262626 guibg=#c9503f gui=NONE cterm=NONE
hi ModeMsg guifg=#007730 guibg=NONE gui=bold cterm=bold
hi MoreMsg guifg=#f2d07f guibg=NONE gui=NONE cterm=NONE
hi Question guifg=#f2d07f guibg=NONE gui=NONE cterm=NONE
hi WarningMsg guifg=#c9503f guibg=NONE gui=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#000000 gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#303030 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#303030 gui=NONE cterm=NONE
hi QuickFixLine guifg=#262626 guibg=#f2d07f gui=NONE cterm=NONE
hi StatusLine guifg=#d0d0d0 guibg=#444444 gui=NONE cterm=NONE
hi StatusLineNC guifg=#949494 guibg=#3a3a3a gui=NONE cterm=NONE
hi VertSplit guifg=#3a3a3a guibg=#3a3a3a gui=NONE cterm=NONE
hi WildMenu guifg=#eeeeee guibg=#6c6c6c gui=NONE cterm=NONE
hi IncSearch guifg=#262626 guibg=#ee6900 gui=NONE cterm=NONE
hi Search guifg=#262626 guibg=#e5a100 gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#3a3a3a gui=NONE cterm=NONE
hi DiffAdd guifg=#689b30 guibg=#3a3a3a gui=NONE cterm=NONE
hi DiffChange guifg=NONE guibg=#3a3a3a gui=NONE cterm=NONE
hi DiffDelete guifg=#c9503f guibg=#3a3a3a gui=NONE cterm=NONE
hi DiffText guifg=#ee6900 guibg=#444444 gui=NONE cterm=NONE
hi Comment guifg=#6c6c6c guibg=NONE gui=italic cterm=italic
hi Constant guifg=#f2d07f guibg=NONE gui=bold cterm=bold
hi Error guifg=#262626 guibg=#c9503f gui=NONE cterm=NONE
hi Identifier guifg=#aea1b7 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#c9503f guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#6d557e guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#2f77a5 guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#6d557e guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi Directory guifg=#19717e guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#aea1b7 guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#ee6900 guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#949494 guibg=NONE gui=italic cterm=italic
hi String guifg=#689b30 guibg=NONE gui=NONE cterm=NONE
hi Title guifg=#d0d0d0 guibg=NONE gui=bold cterm=bold
hi Todo guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#7fabc7 guibg=NONE gui=underline cterm=underline
hi SpellBad guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellCap guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellLocal guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellRare guifg=NONE guibg=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi! link Terminal Normal
hi! link TabLine StatusLineNC
hi! link TabLineFill StatusLineNC
hi! link TabLineSel StatusLine
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link VisualNOS Visual
hi! link diffAdded DiffAdd
hi! link diffBDiffer WarningMsg
hi! link diffChanged DiffChange
hi! link diffCommon WarningMsg
hi! link diffDiffer WarningMsg
hi! link diffFile Directory
hi! link diffIdentical WarningMsg
hi! link diffIndexLine Number
hi! link diffIsA WarningMsg
hi! link diffNoEOL WarningMsg
hi! link diffOnly WarningMsg
hi! link diffRemoved DiffDelete
hi! link Boolean Constant
hi! link Character String
hi! link Float Number
hi! link Conditional Statement
hi! link Exception Statement
hi! link Keyword Statement
hi! link Label Statement
hi! link Operator Statement
hi! link Repeat Statement
hi! link Define PreProc
hi! link Include PreProc
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link StorageClass Type
hi! link Structure Type
hi! link Typedef Type
hi! link Debug Special
hi! link SpecialChar Special
hi! link Tag Special
hi! link Noise Delimiter
hi! link StringDelimiter Delimiter
hi! link Conceal Ignore
hi! link NonText Ignore
hi! link SpecialKey Ignore
hi! link EndOfBuffer Ignore
hi! link Whitespace Ignore
hi! link Searchlight IncSearch
hi! link cssBraces Delimiter
hi! link gitcommitOverflow Error
hi! link gitcommitSummary Title
hi! link helpHyperTextJump Underlined
hi! link htmlEndTag Delimiter
hi! link htmlLink Underlined
hi! link htmlSpecialTagName htmlTagName
hi! link htmlTag Delimiter
hi! link htmlTagName Statement
hi! link rustAttribute Delimiter
hi! link rustDerive rustAttribute
hi! link rustDeriveTrait rustDerive
hi! link rustIdentifier Typedef
hi! link rustModPath None
hi! link scssAttribute Delimiter
hi! link vimAutoCmdSfxList Type
hi! link vimAutoEventList Identifier
hi! link vimCmdSep Special
hi! link vimCommentTitle SpecialComment
hi! link vimHighlight Statement
hi! link vimUserFunc Function
if !s:italics
  hi Comment gui=NONE cterm=NONE
  hi SpecialComment gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  hi Normal ctermfg=255 ctermbg=16 cterm=NONE
  hi Cursor ctermfg=235 ctermbg=255 cterm=NONE
  hi None ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=252 ctermbg=237 cterm=NONE
  hi FoldColumn ctermfg=242 ctermbg=16 cterm=NONE
  hi Folded ctermfg=242 ctermbg=16 cterm=NONE
  hi LineNr ctermfg=242 ctermbg=16 cterm=NONE
  hi MatchParen ctermfg=255 ctermbg=16 cterm=bold
  hi SignColumn ctermfg=242 ctermbg=16 cterm=NONE
  hi Ignore ctermfg=240 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=246 ctermbg=237 cterm=NONE
  hi PmenuSbar ctermfg=16 ctermbg=16 cterm=NONE
  hi PmenuSel ctermfg=255 ctermbg=238 cterm=NONE
  hi PmenuThumb ctermfg=240 ctermbg=240 cterm=NONE
  hi ErrorMsg ctermfg=235 ctermbg=167 cterm=NONE
  hi ModeMsg ctermfg=28 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=222 ctermbg=NONE cterm=NONE
  hi Question ctermfg=222 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=16 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi QuickFixLine ctermfg=235 ctermbg=222 cterm=NONE
  hi StatusLine ctermfg=252 ctermbg=238 cterm=NONE
  hi StatusLineNC ctermfg=246 ctermbg=237 cterm=NONE
  hi VertSplit ctermfg=237 ctermbg=237 cterm=NONE
  hi WildMenu ctermfg=255 ctermbg=242 cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=202 cterm=NONE
  hi Search ctermfg=235 ctermbg=214 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=70 ctermbg=237 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffDelete ctermfg=167 ctermbg=237 cterm=NONE
  hi DiffText ctermfg=202 ctermbg=238 cterm=NONE
  hi Comment ctermfg=242 ctermbg=NONE cterm=italic
  hi Constant ctermfg=222 ctermbg=NONE cterm=bold
  hi Error ctermfg=235 ctermbg=167 cterm=NONE
  hi Identifier ctermfg=146 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=167 ctermbg=NONE cterm=NONE
  hi Special ctermfg=96 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=67 ctermbg=NONE cterm=NONE
  hi Type ctermfg=96 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=246 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=23 ctermbg=NONE cterm=NONE
  hi Function ctermfg=146 ctermbg=NONE cterm=NONE
  hi Number ctermfg=202 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=246 ctermbg=NONE cterm=italic
  hi String ctermfg=70 ctermbg=NONE cterm=NONE
  hi Title ctermfg=252 ctermbg=NONE cterm=bold
  hi Todo ctermfg=255 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=74 ctermbg=NONE cterm=underline
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi! link Terminal Normal
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VisualNOS Visual
  hi! link diffAdded DiffAdd
  hi! link diffBDiffer WarningMsg
  hi! link diffChanged DiffChange
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffFile Directory
  hi! link diffIdentical WarningMsg
  hi! link diffIndexLine Number
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved DiffDelete
  hi! link Boolean Constant
  hi! link Character String
  hi! link Float Number
  hi! link Conditional Statement
  hi! link Exception Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Operator Statement
  hi! link Repeat Statement
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi! link Debug Special
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link Noise Delimiter
  hi! link StringDelimiter Delimiter
  hi! link Conceal Ignore
  hi! link NonText Ignore
  hi! link SpecialKey Ignore
  hi! link EndOfBuffer Ignore
  hi! link Whitespace Ignore
  hi! link Searchlight IncSearch
  hi! link cssBraces Delimiter
  hi! link gitcommitOverflow Error
  hi! link gitcommitSummary Title
  hi! link helpHyperTextJump Underlined
  hi! link htmlEndTag Delimiter
  hi! link htmlLink Underlined
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag Delimiter
  hi! link htmlTagName Statement
  hi! link rustAttribute Delimiter
  hi! link rustDerive rustAttribute
  hi! link rustDeriveTrait rustDerive
  hi! link rustIdentifier Typedef
  hi! link rustModPath None
  hi! link scssAttribute Delimiter
  hi! link vimAutoCmdSfxList Type
  hi! link vimAutoEventList Identifier
  hi! link vimCmdSep Special
  hi! link vimCommentTitle SpecialComment
  hi! link vimHighlight Statement
  hi! link vimUserFunc Function
  if !s:italics
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background:    dark
" Color: base0    #000000 ~
" Color: base1    #262626 ~
" Color: base2    #303030 ~
" Color: base3    #3a3a3a ~
" Color: base4    #444444 ~
" Color: base5    #585858 ~
" Color: base6    #6c6c6c ~
" Color: base7    #949494 ~
" Color: base8    #d0d0d0 ~
" Color: base9    #eeeeee ~
" Color: red      #C9503F ~
" Color: blue     #2f77a5 ~
" Color: pink     #c87e74 ~
" Color: yellow   #e5a100 ~
" Color: green    #007730 ~
" Color: lime     #689b30 ~
" Color: purple   #6d557e ~
" Color: orange   #ee6900 ~
" Color: teal     #19717e ~
" Color: mint     #7fa580 ~
" Color: lemon    #f2d07f ~
" Color: azure    #7fabc7 ~
" Color: lavender #aea1b7 ~
" Term colors: base3 red      green yellow
" Term colors: blue  purple   teal  base8
" Term colors: base6 pink     lime  lemon
" Term colors: azure lavender mint  base9
" vim: et ts=8 sw=2 sts=2
